### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by jiguantong** [subapidao/airnode-config#14]
- [x] https://github.com/darwinia-network/darwinia-airnode/issues/13
- [x] https://github.com/darwinia-network/darwinia-airnode/issues/4
- [x] https://github.com/darwinia-network/airnode-dapi/issues/6
